services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQl_DATABASE: moviehunt

    ports:
      - "3308:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: netflix-clone-api
    container_name: netflix-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviehunt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    volumes:
      - ./uploads/videos:/app/uploads/videos
      - ./uploads/images:/app/uploads/images


volumes:
  mysql-data: